/*
 * Dialog.java
 *
 * Created on __DATE__, __TIME__
 */

package yongbo.tan.autoquery;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.beans.PropertyChangeListener;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.swing.Action;
import javax.swing.ButtonGroup;
import javax.swing.JCheckBox;

import org.apache.commons.lang3.time.FastDateFormat;

import yongbo.tan.client.CustomHttpClient;
import yongbo.tan.js.DynamicJsFetcher;
import yongbo.tan.js.Js;
import yongbo.tan.passenger.PassengerContact;
import yongbo.tan.passenger.PassengerContactFetcher;
import yongbo.tan.passenger.Purpose_Codes;
import yongbo.tan.query.QueryPageFetcher;
import yongbo.tan.signin.DynamicJsFormInput;

/**
 *
 * @author  __USER__
 */
public class QueryDialog extends javax.swing.JDialog {

	FastDateFormat fastDateFormat=FastDateFormat.getInstance("yyyy-MM-dd");
	 
	private CustomHttpClient customHttpClient=new CustomHttpClient();
	
	private QueryPageFetcher queryPageFetcher;
	
	private DynamicJsFormInput dynamicJsFormInput;
	
	
	private List<PassengerContact> passengerContacts;
	
	private String selectPassengerStyle;
	
	private	List<JCheckBox> trainSelections;
	
	private	List<JCheckBox> seatSelections;
	
	
	
	public List<JCheckBox> getTrainSelections() {
		return trainSelections;
	}

	public void setTrainSelections(List<JCheckBox> trainSelections) {
		this.trainSelections = trainSelections;
	}

	public List<JCheckBox> getSeatSelections() {
		return seatSelections;
	}

	public void setSeatSelections(List<JCheckBox> seatSelections) {
		this.seatSelections = seatSelections;
	}

	public String getSelectPassengerStyle() {
		return selectPassengerStyle;
	}

	public void setSelectPassengerStyle(String selectPassengerStyle) {
		this.selectPassengerStyle = selectPassengerStyle;
	}

	/** Creates new form Dialog */
	public QueryDialog(java.awt.Frame parent, boolean modal) {
		
		super(parent, modal);
		queryPageFetcher=new QueryPageFetcher(customHttpClient);
		try {
			
		String  queryPage=queryPageFetcher.gotoQueryViewPage();
		String queryDynamicJsUrl=Js.getDynamicJsUrl(queryPage);
		DynamicJsFetcher dynamicJsFetcher=new DynamicJsFetcher(customHttpClient);
	    dynamicJsFormInput =  dynamicJsFetcher.getDynamicJsInputKeyVal(queryDynamicJsUrl);
	    while(dynamicJsFormInput==null){
	    	dynamicJsFormInput =  dynamicJsFetcher.getDynamicJsInputKeyVal(queryDynamicJsUrl);
	    }
	    System.err.println(dynamicJsFormInput.toString());
	    passengerContacts=PassengerContactFetcher.fetchPassengerContact(customHttpClient);
		} catch (Exception e) {
			e.printStackTrace();
		}
		initComponents();
		
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		departureTime = new javax.swing.JTextField();
		jLabel5 = new javax.swing.JLabel();
		trainSelections	=new ArrayList<JCheckBox>();
		trainSelections.add(gTrain);
		trainSelections.add(dTrain);
		trainSelections.add(zTrain);
		trainSelections.add(tTrain);
		trainSelections.add(kTrain);
		trainSelections.add(qtTrain);
		
		gTrain = new javax.swing.JCheckBox();
		dTrain = new javax.swing.JCheckBox();
		zTrain = new javax.swing.JCheckBox();
		tTrain = new javax.swing.JCheckBox();
		kTrain = new javax.swing.JCheckBox();
		qtTrain = new javax.swing.JCheckBox();
		jLabel6 = new javax.swing.JLabel();
		passenger = new javax.swing.JComboBox();
		jLabel7 = new javax.swing.JLabel();
		trainNo = new javax.swing.JTextField();
		jLabel8 = new javax.swing.JLabel();
		jLabel9 = new javax.swing.JLabel();
		proritySetting = new javax.swing.JComboBox();
		query = new javax.swing.JButton();
		jLabel10 = new javax.swing.JLabel();
		adult = new javax.swing.JRadioButton();
		student = new javax.swing.JRadioButton();
		
	    passengerStyle=	new ButtonGroup() ;
		passengerStyle.add(adult);
		passengerStyle.add(student);
		startTrainStation = new javax.swing.JTextField();
		endTrainStation = new javax.swing.JTextField();
		
		seatSelections=new ArrayList<JCheckBox>();
		seatSelections.add(swzSeat);
		seatSelections.add(tzSeat);
		seatSelections.add(zySeat);
		seatSelections.add(zeSeat);
		seatSelections.add(grSeat);
		seatSelections.add(rwSeat);
		seatSelections.add(yzSeat);
		seatSelections.add(srrbSeat);
		seatSelections.add(yyrwSeat);
		seatSelections.add(rzSeat);
		seatSelections.add(ywSeat);
		seatSelections.add(wzSeat);
		
		swzSeat = new javax.swing.JCheckBox();
		tzSeat = new javax.swing.JCheckBox();
		zySeat = new javax.swing.JCheckBox();
		zeSeat = new javax.swing.JCheckBox();
		grSeat = new javax.swing.JCheckBox();
		rwSeat = new javax.swing.JCheckBox();
		yzSeat = new javax.swing.JCheckBox();
		srrbSeat = new javax.swing.JCheckBox();
		yyrwSeat = new javax.swing.JCheckBox();
		rzSeat = new javax.swing.JCheckBox();
		ywSeat = new javax.swing.JCheckBox();
		wzSeat = new javax.swing.JCheckBox();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

		jLabel1.setText("\u5355\u7a0b");

		jLabel2.setText("\u51fa\u53d1\u5730");

		jLabel3.setText("\u76ee\u7684\u5730");

		jLabel4.setText("\u51fa\u53d1\u65e5");

		departureTime.setText(fastDateFormat.format(new Date()));
		departureTime.setToolTipText("2100-01-01");

		jLabel5.setText("\u8f66\u6b21\u7c7b\u578b");

		gTrain.setText("GC-高铁/城际");

		dTrain.setText("D-动车");

		zTrain.setText("Z-直达");

		tTrain.setText("T-特快");

		kTrain.setText("K-快速");

		qtTrain.setText("其它");

		jLabel6.setText("\u4e58\u8f66\u4eba");
		String[]passengerLable=new String[passengerContacts.size()];
		for(int i=0;i<passengerContacts.size();i++){
			passengerLable[i]=passengerContacts.get(i).getPassenger_name();
		}
				 
		passenger.setModel(new javax.swing.DefaultComboBoxModel(passengerLable));
		 
		jLabel7.setText("\u4f18\u5148\u8f66\u6b21");

		trainNo.setText("请输入车次");
		trainNo.setToolTipText("请输入车次");
		jLabel8.setText("\u4f18\u5148\u5e2d\u522b");

		jLabel9.setText("\u9ad8\u7ea7\u8bbe\u7f6e");

		proritySetting.setModel(new javax.swing.DefaultComboBoxModel(
				new String[] { "席别优先", "车次有先"}));

		query.setText("\u67e5\u8be2");
		query.addActionListener(new QueryTicketButtonAction(this));

		jLabel10.setText("\u7c7b\u578b");

		adult.setText("普通");
		adult.setSelected(true);
		adult.setActionCommand(Purpose_Codes.ADULT.getLabel());
		adult.addActionListener(new ActionListener() {
			
			@Override
			public void actionPerformed(ActionEvent e) {
				selectPassengerStyle=	e.getActionCommand();
			}
		});
		student.setText("学生");
		student.setActionCommand(Purpose_Codes.STUDENT.getLabel());
		student.addActionListener(new ActionListener() {
			
			@Override
			public void actionPerformed(ActionEvent e) {
				 
				selectPassengerStyle=	e.getActionCommand();
			}
		});
   
		startTrainStation.setText("广州");
		startTrainStation.setToolTipText("请输入出发站点");
		
		endTrainStation.setText("娄底");
		endTrainStation.setToolTipText("请输入目的站点");
		
		swzSeat.setText("商务座");

		tzSeat.setText("特等座");

		zySeat.setText("一等座");

		zeSeat.setText("二等座");

		grSeat.setText("高级软卧");

		rwSeat.setText("软卧");

		srrbSeat.setText("动卧");

		yyrwSeat.setText("高级动卧");

		rzSeat.setText("软座");

		ywSeat.setText("硬卧");
	 
		wzSeat.setText("无座");
		
		yzSeat.setText("硬座");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout
				.setHorizontalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout
										.createSequentialGroup()
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addContainerGap()
																		.addGroup(
																				layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addGroup(
																								layout
																										.createSequentialGroup()
																										.addComponent(
																												jLabel1)
																										.addGap(
																												26,
																												26,
																												26)
																										.addComponent(
																												jLabel2)
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																										.addComponent(
																												startTrainStation,
																												javax.swing.GroupLayout.DEFAULT_SIZE,
																												130,
																												Short.MAX_VALUE)
																										.addGap(
																												18,
																												18,
																												18)
																										.addComponent(
																												jLabel3))
																						.addGroup(
																								javax.swing.GroupLayout.Alignment.TRAILING,
																								layout
																										.createSequentialGroup()
																										.addGroup(
																												layout
																														.createParallelGroup(
																																javax.swing.GroupLayout.Alignment.LEADING)
																														.addGroup(
																																layout
																																		.createSequentialGroup()
																																		.addComponent(
																																				jLabel5)
																																		.addPreferredGap(
																																				javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																																				52,
																																				Short.MAX_VALUE)
																																		.addComponent(
																																				gTrain)
																																		.addGap(
																																				18,
																																				18,
																																				18))
																														.addGroup(
																																layout
																																		.createSequentialGroup()
																																		.addGroup(
																																				layout
																																						.createParallelGroup(
																																								javax.swing.GroupLayout.Alignment.LEADING)
																																						.addComponent(
																																								jLabel7)
																																						.addComponent(
																																								jLabel6))
																																		.addGroup(
																																				layout
																																						.createParallelGroup(
																																								javax.swing.GroupLayout.Alignment.LEADING)
																																						.addGroup(
																																								layout
																																										.createSequentialGroup()
																																										.addPreferredGap(
																																												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																																										.addComponent(
																																												passenger,
																																												javax.swing.GroupLayout.PREFERRED_SIZE,
																																												93,
																																												javax.swing.GroupLayout.PREFERRED_SIZE))
																																						.addGroup(
																																								layout
																																										.createSequentialGroup()
																																										.addGap(
																																												15,
																																												15,
																																												15)
																																										.addComponent(
																																												trainNo,
																																												javax.swing.GroupLayout.PREFERRED_SIZE,
																																												javax.swing.GroupLayout.DEFAULT_SIZE,
																																												javax.swing.GroupLayout.PREFERRED_SIZE)))
																																		.addGap(
																																				50,
																																				50,
																																				50)))
																										.addGroup(
																												layout
																														.createParallelGroup(
																																javax.swing.GroupLayout.Alignment.LEADING)
																														.addComponent(
																																jLabel10)
																														.addComponent(
																																dTrain))))
																		.addGroup(
																				layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addGroup(
																								layout
																										.createSequentialGroup()
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																										.addGroup(
																												layout
																														.createParallelGroup(
																																javax.swing.GroupLayout.Alignment.LEADING)
																														.addComponent(
																																adult)
																														.addComponent(
																																zTrain))
																										.addGap(
																												18,
																												18,
																												18)
																										.addGroup(
																												layout
																														.createParallelGroup(
																																javax.swing.GroupLayout.Alignment.LEADING)
																														.addComponent(
																																student)
																														.addComponent(
																																tTrain))
																										.addGap(
																												49,
																												49,
																												49))
																						.addGroup(
																								layout
																										.createSequentialGroup()
																										.addGap(
																												14,
																												14,
																												14)
																										.addComponent(
																												endTrainStation,
																												javax.swing.GroupLayout.DEFAULT_SIZE,
																												200,
																												Short.MAX_VALUE)))
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addGroup(
																				layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING,
																								false)
																						.addGroup(
																								layout
																										.createSequentialGroup()
																										.addGap(
																												32,
																												32,
																												32)
																										.addComponent(
																												kTrain)
																										.addGap(
																												18,
																												18,
																												18)
																										.addComponent(
																												qtTrain,
																												javax.swing.GroupLayout.DEFAULT_SIZE,
																												javax.swing.GroupLayout.DEFAULT_SIZE,
																												Short.MAX_VALUE))
																						.addGroup(
																								layout
																										.createSequentialGroup()
																										.addGap(
																												13,
																												13,
																												13)
																										.addComponent(
																												jLabel4)
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																										.addComponent(
																												departureTime,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												119,
																												javax.swing.GroupLayout.PREFERRED_SIZE))))
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addGap(
																				230,
																				230,
																				230)
																		.addComponent(
																				query,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				121,
																				javax.swing.GroupLayout.PREFERRED_SIZE))
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addContainerGap()
																		.addComponent(
																				jLabel9)
																		.addGap(
																				18,
																				18,
																				18)
																		.addComponent(
																				proritySetting,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				110,
																				javax.swing.GroupLayout.PREFERRED_SIZE))
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addContainerGap()
																		.addComponent(
																				jLabel8)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addGroup(
																				layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addGroup(
																								layout
																										.createSequentialGroup()
																										.addComponent(
																												rzSeat)
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																										.addComponent(
																												ywSeat)
																										.addGap(
																												18,
																												18,
																												18)
																										.addComponent(
																												wzSeat))
																						.addGroup(
																								layout
																										.createSequentialGroup()
																										.addComponent(
																												swzSeat)
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																										.addComponent(
																												tzSeat)
																										.addGap(
																												0,
																												0,
																												0)
																										.addComponent(
																												zySeat)
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																										.addComponent(
																												zeSeat)
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																										.addComponent(
																												grSeat)
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																										.addComponent(
																												rwSeat)
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																										.addComponent(
																												yzSeat)
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																										.addComponent(
																												srrbSeat)
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																										.addComponent(
																												yyrwSeat)))))
										.addContainerGap()));
		layout
				.setVerticalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel1)
														.addComponent(jLabel2)
														.addComponent(jLabel3)
														.addComponent(jLabel4)
														.addComponent(
																departureTime,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																endTrainStation,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																startTrainStation,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(29, 29, 29)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel5)
														.addComponent(dTrain)
														.addComponent(gTrain)
														.addComponent(zTrain)
														.addComponent(tTrain)
														.addComponent(kTrain)
														.addComponent(qtTrain))
										.addGap(27, 27, 27)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																passenger,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabel6)
														.addComponent(jLabel10)
														.addComponent(adult)
														.addComponent(student))
										.addGap(30, 30, 30)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel7)
														.addComponent(
																trainNo,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(18, 18, 18)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel8)
														.addComponent(swzSeat)
														.addComponent(tzSeat)
														.addComponent(zySeat)
														.addComponent(zeSeat)
														.addComponent(grSeat)
														.addComponent(rwSeat)
														.addComponent(
																yzSeat)
														.addComponent(srrbSeat)
														.addComponent(yyrwSeat))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												6, Short.MAX_VALUE)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(rzSeat)
														.addComponent(ywSeat)
														.addComponent(wzSeat))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel9)
														.addComponent(
																proritySetting,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(12, 12, 12).addComponent(
												query).addContainerGap()));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				QueryDialog dialog = new QueryDialog(new javax.swing.JFrame(),
						true);
				dialog.addWindowListener(new java.awt.event.WindowAdapter() {
					public void windowClosing(java.awt.event.WindowEvent e) {
						System.exit(0);
					}
				});
				dialog.setVisible(true);
			}
		});
	}

	
	
	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JRadioButton adult;
	private ButtonGroup passengerStyle;

	private javax.swing.JCheckBox dTrain;
	private javax.swing.JTextField departureTime;
	private javax.swing.JTextField endTrainStation;
	private javax.swing.JCheckBox gTrain;
	private javax.swing.JCheckBox grSeat;
	private javax.swing.JButton query;
	private javax.swing.JCheckBox yzSeat;
	private javax.swing.JComboBox passenger;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel10;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JLabel jLabel9;
	private javax.swing.JTextField trainNo;
	private javax.swing.JCheckBox kTrain;
	private javax.swing.JComboBox proritySetting;
	private javax.swing.JCheckBox qtTrain;
	private javax.swing.JCheckBox rwSeat;
	private javax.swing.JCheckBox rzSeat;
	private javax.swing.JCheckBox srrbSeat;
	private javax.swing.JTextField startTrainStation;
	private javax.swing.JRadioButton student;
	private javax.swing.JCheckBox swzSeat;
	private javax.swing.JCheckBox tTrain;
	private javax.swing.JCheckBox tzSeat;
	private javax.swing.JCheckBox wzSeat;
	private javax.swing.JCheckBox ywSeat;
	private javax.swing.JCheckBox yyrwSeat;
	private javax.swing.JCheckBox zTrain;
	private javax.swing.JCheckBox zeSeat;
	private javax.swing.JCheckBox zySeat;
	// End of variables declaration//GEN-END:variables
	public CustomHttpClient getCustomHttpClient() {
		return customHttpClient;
	}

	public void setCustomHttpClient(CustomHttpClient customHttpClient) {
		this.customHttpClient = customHttpClient;
	}

	public QueryPageFetcher getQueryPageFetcher() {
		return queryPageFetcher;
	}

	public void setQueryPageFetcher(QueryPageFetcher queryPageFetcher) {
		this.queryPageFetcher = queryPageFetcher;
	}

	public DynamicJsFormInput getDynamicJsFormInput() {
		return dynamicJsFormInput;
	}

	public void setDynamicJsFormInput(DynamicJsFormInput dynamicJsFormInput) {
		this.dynamicJsFormInput = dynamicJsFormInput;
	}

	public List<PassengerContact> getPassengerContacts() {
		return passengerContacts;
	}

	public void setPassengerContacts(List<PassengerContact> passengerContacts) {
		this.passengerContacts = passengerContacts;
	}

	public javax.swing.JRadioButton getAdult() {
		return adult;
	}

	public void setAdult(javax.swing.JRadioButton adult) {
		this.adult = adult;
	}

	public ButtonGroup getPassengerStyle() {
		return passengerStyle;
	}

	public void setPassengerStyle(ButtonGroup passengerStyle) {
		this.passengerStyle = passengerStyle;
	}

	public javax.swing.JCheckBox getdTrain() {
		return dTrain;
	}

	public void setdTrain(javax.swing.JCheckBox dTrain) {
		this.dTrain = dTrain;
	}

	public javax.swing.JTextField getDepartureTime() {
		return departureTime;
	}

	public void setDepartureTime(javax.swing.JTextField departureTime) {
		this.departureTime = departureTime;
	}

	public javax.swing.JTextField getEndTrainStation() {
		return endTrainStation;
	}

	public void setEndTrainStation(javax.swing.JTextField endTrainStation) {
		this.endTrainStation = endTrainStation;
	}

	public javax.swing.JCheckBox getgTrain() {
		return gTrain;
	}

	public void setgTrain(javax.swing.JCheckBox gTrain) {
		this.gTrain = gTrain;
	}

	public javax.swing.JCheckBox getGrSeat() {
		return grSeat;
	}

	public void setGrSeat(javax.swing.JCheckBox grSeat) {
		this.grSeat = grSeat;
	}

	public javax.swing.JButton getQuery() {
		return query;
	}

	public void setQuery(javax.swing.JButton query) {
		this.query = query;
	}

	public javax.swing.JCheckBox getYzSeat() {
		return yzSeat;
	}

	public void setYzSeat(javax.swing.JCheckBox yzSeat) {
		this.yzSeat = yzSeat;
	}

	public javax.swing.JComboBox getPassenger() {
		return passenger;
	}

	public void setPassenger(javax.swing.JComboBox passenger) {
		this.passenger = passenger;
	}

	public javax.swing.JTextField getTrainNo() {
		return trainNo;
	}

	public void setTrainNo(javax.swing.JTextField trainNo) {
		this.trainNo = trainNo;
	}

	public javax.swing.JCheckBox getkTrain() {
		return kTrain;
	}

	public void setkTrain(javax.swing.JCheckBox kTrain) {
		this.kTrain = kTrain;
	}

	public javax.swing.JComboBox getProritySetting() {
		return proritySetting;
	}

	public void setProritySetting(javax.swing.JComboBox proritySetting) {
		this.proritySetting = proritySetting;
	}

	public javax.swing.JCheckBox getQtTrain() {
		return qtTrain;
	}

	public void setQtTrain(javax.swing.JCheckBox qtTrain) {
		this.qtTrain = qtTrain;
	}

	public javax.swing.JCheckBox getRwSeat() {
		return rwSeat;
	}

	public void setRwSeat(javax.swing.JCheckBox rwSeat) {
		this.rwSeat = rwSeat;
	}

	public javax.swing.JCheckBox getRzSeat() {
		return rzSeat;
	}

	public void setRzSeat(javax.swing.JCheckBox rzSeat) {
		this.rzSeat = rzSeat;
	}

	public javax.swing.JCheckBox getSrrbSeat() {
		return srrbSeat;
	}

	public void setSrrbSeat(javax.swing.JCheckBox srrbSeat) {
		this.srrbSeat = srrbSeat;
	}

	public javax.swing.JTextField getStartTrainStation() {
		return startTrainStation;
	}

	public void setStartTrainStation(javax.swing.JTextField startTrainStation) {
		this.startTrainStation = startTrainStation;
	}

	public javax.swing.JRadioButton getStudent() {
		return student;
	}

	public void setStudent(javax.swing.JRadioButton student) {
		this.student = student;
	}

	public javax.swing.JCheckBox getSwzSeat() {
		return swzSeat;
	}

	public void setSwzSeat(javax.swing.JCheckBox swzSeat) {
		this.swzSeat = swzSeat;
	}

	public javax.swing.JCheckBox gettTrain() {
		return tTrain;
	}

	public void settTrain(javax.swing.JCheckBox tTrain) {
		this.tTrain = tTrain;
	}

	public javax.swing.JCheckBox getTzSeat() {
		return tzSeat;
	}

	public void setTzSeat(javax.swing.JCheckBox tzSeat) {
		this.tzSeat = tzSeat;
	}

	public javax.swing.JCheckBox getWzSeat() {
		return wzSeat;
	}

	public void setWzSeat(javax.swing.JCheckBox wzSeat) {
		this.wzSeat = wzSeat;
	}

	public javax.swing.JCheckBox getYwSeat() {
		return ywSeat;
	}

	public void setYwSeat(javax.swing.JCheckBox ywSeat) {
		this.ywSeat = ywSeat;
	}

	public javax.swing.JCheckBox getYyrwSeat() {
		return yyrwSeat;
	}

	public void setYyrwSeat(javax.swing.JCheckBox yyrwSeat) {
		this.yyrwSeat = yyrwSeat;
	}

	public javax.swing.JCheckBox getzTrain() {
		return zTrain;
	}

	public void setzTrain(javax.swing.JCheckBox zTrain) {
		this.zTrain = zTrain;
	}

	public javax.swing.JCheckBox getZeSeat() {
		return zeSeat;
	}

	public void setZeSeat(javax.swing.JCheckBox zeSeat) {
		this.zeSeat = zeSeat;
	}

	public javax.swing.JCheckBox getZySeat() {
		return zySeat;
	}

	public void setZySeat(javax.swing.JCheckBox zySeat) {
		this.zySeat = zySeat;
	}
    
}